language: r
cache: packages

bioc_packages:
   - Rgraphviz

# Be strict when checking our package
warnings_are_errors: true

r_check_args: -no-manual --no-build-vignettes --run-donttest
#--as-cran --run-donttest 
